### ISSUE TITLE
chinese word or chinese character

### ISSUE THREAD

**Issue by liuwei1206** [lemonhu/NER-BERT-pytorch#10]
Hi lemonhu,

I am confused that the Chinese bert model labeling on each Chinese word or Chinese character?
And is there a Chinese wordpiece processing?

**Comment by lemonhu** [comment]
Hi, thanks for posting the question.
It is based on Chinese characters for entity recognition.
Yeah, Google's Bert model provides a Chinese wordpiece processing. You can see the code `tokenized_text = tokenizer.tokenize(text)` in link [pytorch-pretrained-BERT#usage](https://github.com/huggingface/pytorch-pretrained-BERT#usage)
