### ISSUE TITLE
tokenizer

### ISSUE THREAD

**Issue by zhangatao** [lemonhu/NER-BERT-pytorch#12]
你好，首先感谢你把代码开放出来，代码写的很优雅，但是我有个疑问，我看你在处理分词的时候，用的是bert自带的tokenizer，也就是WordpieceTokenizer，但是这样会出现字符合并的现象，就ner这种任务，是不是需要做一些处理来保证分词之后的序列能和之前的序列长度保持一致？？

**Comment by lemonhu** [comment]
谢谢关注，规范的处理应该是对`tokenizer .tokenize()`后的token序列进行BIO标注处理的，避免造成错位影响。

**Comment by zhangatao** [comment]
你好，谢谢你的回答，我还有个疑问，就是你的代码中，在构建bert的输入时，没有加入官方的，cls和seq，我的理解是cls代表encode之后，这句话的句向量，seq起到分隔的作用，看到你没有用到这两个标志，是不是在ner这种任务下，这个两个标识符不是必须的？

**Comment by lemonhu** [comment]
在NER任务中，一条数据只包含一个句子(不以显示句号`。`划分)，不需要`[SEP]`token，也不需要对整个句子编码，因此也不需要`[CLS]`toekn进行标识。

**Comment by zhangatao** [comment]
好的，谢谢
