### ISSUE TITLE
How to solve the increasing of tokens when tokenize?

### ISSUE THREAD

**Issue by minhson-kaist** [lemonhu/NER-BERT-pytorch#14]
Hi, 
First I want to thank you for releasing this amazing work.
I am trying to use your work to train another model.

However, I have to deal with the following problem.
In `data_loader` process, when using BERT tokenizer, a word in my training sentence has been splitted into 4 tokens:
`
Courtaulds => ['court', '##au', '##ld', '##s']
`
Can you suggest how to represent the corresponding tag of this word?
Because in the `tag` file, we only have 1 tag per 1 word, when running the assertion to check the length of tag list and token list, it will raise an error.

**Comment by scarydemon2** [comment]
> Hi,
> First I want to thank you for releasing this amazing work.
> I am trying to use your work to train another model.
> 
> However, I have to deal with the following problem.
> In `data_loader` process, when using BERT tokenizer, a word in my training sentence has been splitted into 4 tokens:
> `Courtaulds => ['court', '##au', '##ld', '##s']`
> Can you suggest how to represent the corresponding tag of this word?
> Because in the `tag` file, we only have 1 tag per 1 word, when running the assertion to check the length of tag list and token list, it will raise an error.

Goo question，I want to know if you have solved this problem because I have the same problem now

**Comment by minhson-kaist** [comment]
You have to write additional codes to solve this, like you have to detect whether a token is a part of previous tokens (tokens with ## at the beginning)
