### ISSUE TITLE
大佬我想学习你的代码，这段代码是什么意思呀

### ISSUE THREAD

**Issue by CerryXu** [lemonhu/NER-BERT-pytorch#18]
![WJ~Q3J_IJK}0GD{P(BQ){~T](https://user-images.githubusercontent.com/45084662/68177759-481c5500-ffc4-11e9-9d93-4ccf7bcc7df5.png)

**Comment by lemonhu** [comment]
谢谢关注。
因BERT模型参数量比较大，`full_finetuning`参数的含义是是否对模型的所有参数进行更新。`full_finetuning`为True时，对BERT Encoder及token级别的分类层`classifier`进行参数更新；
`full_finetuning`为False时，仅对token级别的分类层`classifier`进行参数更新；

**Comment by CerryXu** [comment]
> 谢谢关注。
> 因BERT模型参数量比较大，`full_finetuning`参数的含义是是否对模型的所有参数进行更新。`full_finetuning`为True时，对BERT Encoder及token级别的分类层`classifier`进行参数更新；
> `full_finetuning`为False时，仅对token级别的分类层`classifier`进行参数更新；

感谢回答，我把pytorch_pretrained_bert的源码下下来看,发现这里加载方法时候，为什么报红遇见两次这种现象了，但是没找到原因
