### ISSUE TITLE
官方中文BERT权重的链接好像不对

### ISSUE THREAD

**Issue by Healingl** [lemonhu/NER-BERT-pytorch#3]
Download the Google's BERT base model for Chinese from **BERT-Base, Chinese** (Chinese Simplified and Traditional, 12-layer, 768-hidden, 12-heads, 110M parameters), and decompress it.

这里应该是[chinese_L-12_H-768_A-12](https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip)

**Comment by lemonhu** [comment]
谢谢关注与指出，已经更正。
