### ISSUE TITLE
无法复现结果，准确率较低

### ISSUE THREAD

**Issue by lxy444** [lemonhu/NER-BERT-pytorch#4]
按照默认参数运行程序之后，准确率较低，结果如下
`Starting evaluation...
- Test metrics: loss: 00.12; f1: 68.16
             precision    recall  f1-score   support

        ORG      46.25     65.73     54.30      1287
        LOC      66.21     81.61     73.11      2790
        PER      68.62     76.68     72.43      1372

avg / total      62.11     76.62     68.50      5449
`
请问是什么问题呢？

**Comment by lemonhu** [comment]
谢谢您的反馈，具体可以参考如下问题：
#2 
主要原因应该是`pytorch-pretrained-bert`版本问题，建议使用命令`pip install pytorch-pretrained-bert==0.4.0`安装较低版本。

**Comment by lxy444** [comment]
> 谢谢您的反馈，具体可以参考如下问题：
> #2
> 主要原因应该是`pytorch-pretrained-bert`版本问题，建议使用命令`pip install pytorch-pretrained-bert==0.4.0`安装较低版本。

感谢回复，我安装了 0.4.0 版本之后，重新跑了代码，前两轮结果如下：
`Epoch 1/20
100%|██████████| 4200/4200 [10:15<00:00,  6.06it/s, loss=0.387]
- Train metrics: loss: 00.31; f1: 00.00
- Val metrics: loss: 00.32; f1: 00.00
Epoch 2/20
100%|██████████| 4200/4200 [10:16<00:00,  6.23it/s, loss=0.313]
- Train metrics: loss: 00.31; f1: 00.00
- Val metrics: loss: 00.32; f1: 00.00
`

f1 值计算出错，可能是某处代码还需要更新。

**Comment by lemonhu** [comment]
我又重新clone了代码，前两个epoch的结果如下，[依赖库版本](https://github.com/lemonhu/NER-BERT-pytorch/blob/master/requirements.txt)和[默认超参数](https://github.com/lemonhu/NER-BERT-pytorch/blob/master/experiments/base_model/params.json)已更新。

100%|███████████████████████████| 1400/1400 [08:54<00:00,  2.72it/s, loss=0.023]
- Train metrics: loss: 00.01; f1: 94.26
- Val metrics: loss: 00.01; f1: 92.31
- Found new best F1
Epoch 2/20

100%|███████████████████████████| 1400/1400 [08:33<00:00,  2.63it/s, loss=0.007]
- Train metrics: loss: 00.00; f1: 96.90
- Val metrics: loss: 00.01; f1: 94.16
- Found new best F1

你的问题显示网络经过2个epoch，完全没有学习到任何信息，由于我重新运行没有出现这个问题，你自己再查找下问题原因哈，欢迎再次反馈~

**Comment by lxy444** [comment]
> 我又重新clone了代码，前两个epoch的结果如下，[依赖库版本](https://github.com/lemonhu/NER-BERT-pytorch/blob/master/requirements.txt)和[默认超参数](https://github.com/lemonhu/NER-BERT-pytorch/blob/master/experiments/base_model/params.json)已更新。
> 
> 100%|███████████████████████████| 1400/1400 [08:54<00:00, 2.72it/s, loss=0.023]
> 
> * Train metrics: loss: 00.01; f1: 94.26
> * Val metrics: loss: 00.01; f1: 92.31
> * Found new best F1
>   Epoch 2/20
> 
> 100%|███████████████████████████| 1400/1400 [08:33<00:00, 2.63it/s, loss=0.007]
> 
> * Train metrics: loss: 00.00; f1: 96.90
> * Val metrics: loss: 00.01; f1: 94.16
> * Found new best F1
> 
> 你的问题显示网络经过2个epoch，完全没有学习到任何信息，由于我重新运行没有出现这个问题，你自己再查找下问题原因哈，欢迎再次反馈~

十分感谢，已经能够复现，没有问题了，我前两轮的结果如下：

`- Train metrics: loss: 00.01; f1: 94.70
- Val metrics: loss: 00.01; f1: 92.96
- Found new best F1
Epoch 2/20
100%|███████████████████████████| 1400/1400 [06:10<00:00,  3.57it/s, loss=0.007]
- Train metrics: loss: 00.00; f1: 97.02
- Val metrics: loss: 00.01; f1: 94.15
- Found new best F1
`

顺便问一下，你的机器是什么配置呢？我运行程序的时候用四张1080Ti 显卡可以跑，但是如果只用一张卡(不使用 --multi_gpu 参数)，程序在跑完一轮后计算准确率信息时，会报错：


`Epoch 1/20
100%|██████████| 1400/1400 [09:00<00:00,  2.45it/s, loss=0.023]
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    train_and_evaluate(model, train_data, val_data, optimizer, scheduler, params, args.model_dir, args.restore_file)
  File "train.py", line 106, in train_and_evaluate
    train_metrics = evaluate(model, train_data_iterator, params, mark='Train')
  File "/home/lxy/github/NER-BERT-pytorch/evaluate.py", line 52, in evaluate
    batch_output = model(batch_data, token_type_ids=None, attention_mask=batch_masks)  # shape: (batch_size, max_len, num_labels)
  File "/opt/anaconda/3-py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda/3-py36/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 1020, in forward
    sequence_output, _ = self.bert(input_ids, token_type_ids, attention_mask, output_all_encoded_layers=False)
  File "/opt/anaconda/3-py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda/3-py36/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 629, in forward
    output_all_encoded_layers=output_all_encoded_layers)
  File "/opt/anaconda/3-py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda/3-py36/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 330, in forward
    hidden_states = layer_module(hidden_states, attention_mask)
  File "/opt/anaconda/3-py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda/3-py36/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 315, in forward
    attention_output = self.attention(hidden_states, attention_mask)
  File "/opt/anaconda/3-py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda/3-py36/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 275, in forward
    self_output = self.self(input_tensor, attention_mask)
  File "/opt/anaconda/3-py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda/3-py36/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 235, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: CUDA out of memory. Tried to allocate 39.75 MiB (GPU 0; 10.92 GiB total capacity; 9.09 GiB already allocated; 29.50 MiB free; 803.46 MiB cached)
`

提示 cuda 显存不够了，所以想问一下你的机器配置，以及你如果使用单卡跑的话，会有这个报错吗？

**Comment by lemonhu** [comment]
我的机器配置几乎跟你的一样。如果要单卡运行，在[超参数配置文件](https://github.com/lemonhu/NER-BERT-pytorch/blob/master/experiments/base_model/params.json)中减小batch_size即可。

**Comment by lxy444** [comment]
> 我的机器配置几乎跟你的一样。如果要单卡运行，在[超参数配置文件](https://github.com/lemonhu/NER-BERT-pytorch/blob/master/experiments/base_model/params.json)中减小batch_size即可。

感谢提醒，试了一下，只减小 batch_size 可能还不太够，我还调小了 max_len，这样就可以了。

**Comment by Single430** [comment]
@lxy444  @lemonhu   您好，我现在也遇到了上述问题，将版本降到0.4.0后出现f1为０的情况，然后我重新clone 代码，试了很多次f1还是０

找到原因了:  bert_config.json  生成　pytorch_model.bin 以及模型训练　前后要一样

祝您生活愉快
super.single430
