### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Biaocsu** [lemonhu/NER-BERT-pytorch#7]
你好，我在使用python evaluation.py 进行评估时碰到这样的问题，请问这又是什么原因导致的呢？完整运行输出如下：
Loading the dataset...
loading vocabulary file bert-base-chinese-pytorch/vocab.txt
done.
Starting evaluation...
Segmentation fault (core dumped)

**Comment by Biaocsu** [comment]
知道原因了，是我的apex引起的

**Comment by MrRace** [comment]
> 知道原因了，是我的apex引起的

你最后是怎么处理的？是怎么安装的apex???

**Comment by Biaocsu** [comment]
我将CUDA重新安装了，apex安装方法就是按照官方git上的指令，之前出错基本就是因为环境原因

**Comment by MrRace** [comment]
> 我将CUDA重新安装了，apex安装方法就是按照官方git上的指令，之前出错基本就是因为环境原因
重新安装的CUDA版本是多少？所以，你的解决方案是，重新安装CUDA，然后再按照官方教程安装apex？

**Comment by Biaocsu** [comment]
嗯嗯是的。我将Anaconda也重装了，之前python=3.5遇到一个报错，现在忘了啥报错（pytorch官网说了python=3.5会存在该问题），CUDA是版本10
